### ISSUE TITLE
Line updateSettings in chipdrive.py

### ISSUE THREAD

**Issue by AndyThirtover** [pootle/tripipy#2]
Hi there --- I've not go the right board with R1 deleted and this code is working for me.

I've found that updateSettings throws this error:

mot.updateSettings([{'maxrpm':10}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/tripipy/chipdrive.py", line 106, in updateSettings
    if 'stepsPerRev' in upates:
NameError: name 'upates' is not defined

Line 106 has upates instead of updates.

Now I'm trying to work out the settings for the quietest possible drive of a Nema 17 - perhaps a couple of pointers would help and I'll document my findings!

Double Regards

Andy

**Comment by pootle** [comment]
Oops - how did that escape!

To get the fastest speed, test with a fairly slow ramp rate set. Also the higher the driving voltage you can use the better, and use current limiting to stop it heating up - although I've not messed with current limiting on these chips, I used it to good effect on an a4988. The fastest step rate in the datasheet for the motor should be a good starting point. They tend not to have much torque at high speed, so depending on the load you have to drive, you mahy have to back off a bit.

Good luck!
